from .AestheticLoss import AestheticLoss
from .ClipPrompt import ClipPrompt
from .InputImage import InputImage
from .GaussianLoss import GaussianLoss
from .PaletteLoss import PaletteLoss
from .ResmemLoss import ResmemLoss
from .SaturationLoss import SaturationLoss
from .SmoothnessLoss import SmoothnessLoss
from .SymmetryLoss import SymmetryLoss
from .StyleLoss import StyleLoss
from .EdgeLoss import EdgeLoss
